---

- include: repository-yum.yml
  tags: repository
  when: ansible_os_family == 'RedHat'

- include: repository-apt.yml
  tags: repository
  when: ansible_os_family == 'Debian'

- include: packages-yum.yml
  tags: packages
  when: ansible_os_family == 'RedHat'

- include: packages-apt.yml
  tags: packages
  when: ansible_os_family == 'Debian'

- include: logrotate.yml
  tags: [packages,rabbitmq]

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml

- include: service.yml

- include: cluster.yml
  when: (rabbitmq_create_cluster == True) and ( ansible_fqdn != rabbitmq_cluster_master )

- include: rabbitmq.yml
  when: 'not rabbitmq_create_cluster or (ansible_fqdn == rabbitmq_cluster_master)'

- include: rabbitmqadmin.yml
  when: "'rabbitmq_management' in rabbitmq_plugins"

- meta: flush_handlers
