---

- include: repository-yum.yml
  tags: repository
  when: ansible_os_family == 'RedHat'

- include: repository-apt.yml
  tags: repository
  when: ansible_os_family == 'Debian'

- include: packages-yum.yml
  tags: packages
  when: ansible_os_family == 'RedHat'

- include: packages-apt.yml
  tags: packages
  when: ansible_os_family == 'Debian'

- include: logrotate.yml
  tags: [packages,rabbitmq]

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml

- include: service.yml

- include: cluster.yml
  when: (ansible_hostname | lower != rabbitmq_cluster_master | lower) and rabbitmq_create_cluster == True

- include: rabbitmq.yml
  when: (not rabbitmq_create_cluster) or (ansible_hostname | lower == rabbitmq_cluster_master | lower)

- meta: flush_handlers
