---
# Install required packages

- name: install required packages
  apt:
    update_cache: yes
    force: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: install ssl-cert
  apt:
    force: yes
    pkg: ssl-cert 
    state: present
  when: rabbitmq_ssl or rabbitmq_ssl_use_snakeoil_cert

- name: add rabbitmq user to the ssl-cert group
  user: 
    name: rabbitmq 
    append: yes 
    groups: ssl-cert
  when: rabbitmq_ssl or rabbitmq_ssl_use_snakeoil_cert