---
# Setup installation repositories
# Standard repository for Debian / Ubuntu (http://www.rabbitmq.com/install-debian.html)

- name: import repository key
  apt_key:
    url: "{{ rabbitmq_repository_key_url }}"
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb {{ rabbitmq_repository_url }} {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present
